### ISSUE TITLE
BERKEBUN JAGUNG

### ISSUE THREAD

**Issue by Sangngin** [laksanautama/Berkebun-Jagung#1]
om Swastyastu selamat malam pak kussa ini saya Sangngin dengan nim 2313231016 mohon maff AS kemarin,
Fork, clone, trus push origin, baru pull request.
Jadi sy dpt kode yg sdh fix dan tinggal dirunning di komputer saya saja.
![Screenshot (197)](https://github.com/laksanautama/Berkebun-Jagung/assets/156885651/a2250122-8955-48f7-8fb8-31cf04ccd414)

**Comment by laksanautama** [comment]
Tolong Open pull request,
Bukan posting screen shot di menu issue ini.
Tujuannya pull request biar kode yg di konputer saya lgsung terupdate dgn kode ini
